cooking/tasks/urls.py
from django.conf.urls import *
# from django.views.generic.simple import *
from views import *
# Enable admin
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    url(r'^pick$', pick_task, name='pick_task'),
    url(r'^add$', add_task, name='add_task'),
    url(r'^complete$', complete_task, name='complete_task'),
    url(r'^task/(?P<pk>[0-9]+)$', task_detail, name='task_detail'),
    url(r'^', tasks, name='tasks'),
]

cooking/urls.py
from __future__ import unicode_literals

from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.views.i18n import set_language

from mezzanine.core.views import direct_to_template
from mezzanine.conf import settings


admin.autodiscover()

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

urlpatterns = i18n_patterns(
    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    url("^admin/", include(admin.site.urls)),
)

if settings.USE_MODELTRANSLATION:
    urlpatterns += [
        url('^i18n/$', set_language, name='set_language'),
    ]

urlpatterns += [
    # We don't want to presume how your homepage works, so here are a
    # few patterns you can use to set it up.

    # HOMEPAGE AS STATIC TEMPLATE
    # ---------------------------
    # This pattern simply loads the index.html template. It isn't
    # commented out like the others, so it's the default. You only need
    # one homepage pattern, so if you use a different one, comment this
    # one out.

    url("^$", direct_to_template, {"template": "index.html"}, name="home"),

    url(r'^tasks/', include('cooking.tasks.urls')),

    # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
    # ---------------------------------------------
    # This pattern gives us a normal ``Page`` object, so that your
    # homepage can be managed via the page tree in the admin. If you
    # use this pattern, you'll need to create a page in the page tree,
    # and specify its URL (in the Meta Data section) as "/", which
    # is the value used below in the ``{"slug": "/"}`` part.
    # Also note that the normal rule of adding a custom
    # template per page with the template name using the page's slug
    # doesn't apply here, since we can't have a template called
    # "/.html" - so for this case, the template "pages/index.html"
    # should be used if you want to customize the homepage's template.
    # NOTE: Don't forget to import the view function too!

    # url("^$", mezzanine.pages.views.page, {"slug": "/"}, name="home"),

    # HOMEPAGE FOR A BLOG-ONLY SITE
    # -----------------------------
    # This pattern points the homepage to the blog post listing page,
    # and is useful for sites that are primarily blogs. If you use this
    # pattern, you'll also need to set BLOG_SLUG = "" in your
    # ``settings.py`` module, and delete the blog page object from the
    # page tree in the admin if it was installed.
    # NOTE: Don't forget to import the view function too!

    # url("^$", mezzanine.blog.views.blog_post_list, name="home"),

    # MEZZANINE'S URLS
    # ----------------
    # ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
    # ``mezzanine.urls`` INCLUDES A *CATCH ALL* PATTERN
    # FOR PAGES, SO URLPATTERNS ADDED BELOW ``mezzanine.urls``
    # WILL NEVER BE MATCHED!

    # If you'd like more granular control over the patterns in
    # ``mezzanine.urls``, go right ahead and take the parts you want
    # from it, and use them directly below instead of using
    # ``mezzanine.urls``.
    url("^", include("mezzanine.urls")),

    # MOUNTING MEZZANINE UNDER A PREFIX
    # ---------------------------------
    # You can also mount all of Mezzanine's urlpatterns under a
    # URL prefix if desired. When doing this, you need to define the
    # ``SITE_PREFIX`` setting, which will contain the prefix. Eg:
    # SITE_PREFIX = "my/site/prefix"
    # For convenience, and to avoid repeating the prefix, use the
    # commented out pattern below (commenting out the one above of course)
    # which will make use of the ``SITE_PREFIX`` setting. Make sure to
    # add the import ``from django.conf import settings`` to the top
    # of this file as well.
    # Note that for any of the various homepage patterns above, you'll
    # need to use the ``SITE_PREFIX`` setting as well.

    # ("^%s/" % settings.SITE_PREFIX, include("mezzanine.urls"))

]

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

cooking/tasks/models.py
from django.db import models
from django.contrib.auth.models import User


class Task(models.Model):
    title = models.CharField(null=False, max_length=200)
    desc = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    TASK_TYPES = [
        ("Recipe", "Recipe"),
        ("Ingredient", "Ingredient"),
        ("Inspiration", "Inspiration"),  # usually means enjoying someone else's cooking but that helps too!
        ("Nutrition", "Nutrition"),
    ]
    task_type = models.CharField(null=False, default="Recipe", max_length=100, choices=TASK_TYPES)
    TASK_DIFFICULTY = [
        (1, "Easy peasy lemon squeezy (difficulty 1)"),
        (2, "Just don't burn it (difficulty 2)"),
        (3, "Add some flavour (difficulty 3)"),
        (4, "Toss that salad (difficulty 4)"),
        (5, "Drizzle your olive oil from great height (difficulty 5)")
    ]
    diff = models.IntegerField(null=False, default=1, choices=TASK_DIFFICULTY)

    # Will the task appear in Public Tasks
    public = models.BooleanField(default=True)

#     class Meta:
#         abstract = True

    def __unicode__(self):
        # how it shows up in a list on admin interface
        return "Title: " + self.title + ", Type: " + str(self.task_type)


class Character(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    level = models.IntegerField(default=1)
    exp = models.IntegerField(default=0)
    tasks = models.ManyToManyField(Task, through='TaskOwnership', default=None, blank=True)
    difficulty_to_exp = 10  # conversion factor between difficulty and exp

    def __unicode__(self):
        # how it shows up in a list on admin interface
        return "User: " + self.user.username + ", Level: " + str(self.level)

    def update_exp(self, difficulty):
        extra_exp = difficulty * self.difficulty_to_exp
        self.exp += extra_exp
        self.update_level()

    def exp_to_level(self, exp):
        """convert exp to level"""
        return int(exp / 30) + 1

    def update_level(self):
        new_level = self.exp_to_level(self.exp)
        self.level = new_level


class TaskOwnership(models.Model):
    character = models.ForeignKey(Character, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    # Has the task been completed?
    completed = models.BooleanField(default=False)

    def __unicode__(self):
        # how it shows up in a list on admin interface
        return "User: " + self.character.user.username + ", Task: " + self.task.title + ", Completed: " + str(self.completed)

cooking/tasks/forms.py
from django import forms
from django.forms.forms import BoundField
from django.template import Context, loader
from .models import Task


class TaskForm(forms.ModelForm):

    desc = forms.CharField(required=False, widget=forms.Textarea)

    class Meta:
        model = Task
        fields = ('title', 'desc', 'task_type', 'diff', 'public')


class TemplatedForm(forms.ModelForm):
    """
    From http://djangosnippets.org/snippets/121/
    """
    def output_via_template(self):
        """Helper function for fieldsting fields data from form"""

        bound_fields = [BoundField(self, field, name) for name, field in self.fields.items()]

        c = Context(dict(form=self, bound_fields=bound_fields))
        t = loader.get_template('forms/form.html')
        return t.render(c)

    def __unicode__(self):
        return self.output_via_template()

cooking/tasks/views.py
from django.shortcuts import render, get_object_or_404, redirect
from models import Task, TaskOwnership
from forms import TaskForm
from json import dumps
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import user_passes_test, login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import get_user_model


def admin_check(user):
    return user.is_staff


@login_required
@csrf_exempt  # until I figure out how to get CSRF working with JS
# Shows list of tasks for logged in user
def tasks(request):
    user = request.user
    tasks_for_user = user.character.tasks.filter(taskownership__completed=False)
    return render(request, "mine.html", {'tasks': tasks_for_user, 'level': user.character.level,
                                         'exp': user.character.exp})


def task_detail(request, pk):
    task = get_object_or_404(Task, pk=pk)
    return render(request, "task_details.html", {'task': task})


@login_required
def add_task(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        user = request.user
        if form.is_valid():
            task = form.save(commit=False)
            task.save()
            TaskOwnership.objects.create(task=task, character=user.character)
        return redirect('/tasks')
    else:
        form = TaskForm()
        return render(request, "add_task.html", {'form': form})


@login_required
@csrf_exempt  # until I figure out how to get CSRF working with JS
def pick_task(request):
    if request.method == "POST":
        task_id = request.POST.get('ID')
        user = request.user
        task_to_assign = Task.objects.filter(id=task_id)[0]
        TaskOwnership.objects.create(task=task_to_assign, character=user.character)
        # form = TaskForm(request.POST)
        # user = request.user
        # if form.is_valid():
        #     task = form.save(commit=False)
        #     task.save()
        #     user.character.tasks.add(task)
        return redirect('/tasks')
    else:
        task_list = Task.objects.all()
        return render(request, "pick_task.html", {'tasks': task_list})


@login_required
@csrf_exempt  # until I figure out how to get CSRF working with JS
def complete_task(request):
    user = request.user
    if request.method == "POST":  # when complete task is clicked
        task_id = request.POST.get('ID')
        task_to_complete = TaskOwnership.objects.filter(task=task_id, character=user.character)[0]
        task_to_complete.completed = True
        task_to_complete.save()
        user.character.update_exp(task_to_complete.task.diff)
        user.character.save()
    return redirect('/tasks')

cooking/tasks/templates/add_task.html
{% extends "base.html" %}
{% load i18n %}
{% block meta_title %}{% trans "New Task" %}{% endblock %}

{% block main %}

<tbody>
 <tr class="table_row">
     <form action="/tasks/add" method="post">
        {% csrf_token %}
        {% for field in form %}
          <td>
           <table>
            <tr><td>{{ field.label }}</td></tr>
            <tr><td>{{ field }}</td></tr>
           </table>
          </td>
    {% endfor %}
    <input type="submit" value="Submit" />
    </form>
 </tr>
</tbody>

{% endblock %}

cooking/tasks/templates/mine.html
{% extends 'base.html' %}
{% load i18n %}

{% block meta_title %}{% trans "My Tasks" %}{% endblock %}
{% block title %}{% trans "My Tasks" %}{% endblock %}

{% block main %}
    <script>
    function complete(taskID) {
    //     console.log(taskID);
        var form = document.createElement('form');
        form.setAttribute('method', 'post');
        form.setAttribute('action', '/tasks/complete');
        form.style.display = 'hidden';
        var IDField = document.createElement("input");
        IDField.setAttribute("type", "hidden");
        IDField.setAttribute("name", "ID");
        IDField.setAttribute("value", taskID);
        form.appendChild(IDField);
        document.body.appendChild(form)
        form.submit();
    }
    </script>
    <p>Level: {{ level }}</p>
    <p>Exp: {{ exp }}</p>
    <button class="btn btn-info" type="button" onclick="window.location.href='/tasks/pick'">Pick next task</button>
    <button class="btn btn-info" type="button" onclick="window.location.href='/tasks/add'">Add new task</button>
    <p></p>
    {% if not tasks %}
    <p>Looks like your to-do list is empty. Click "pick next" to choose one from a list or "add new" to create your own.</p>
    {% endif %}
    {% for task in tasks %}
        <div class="post">
            <h3><a href="{% url 'task_detail' pk=task.pk %}">{{ task.title }}</a></h3>
            <p>{{ task.desc|linebreaks }}</p>
            <input class="btn btn-success" type="submit" value="Completed" onclick="complete('{{task.id}}')">
        </div>
    {% endfor %}
{% endblock main %}

cooking/tasks/templates/pick_task.html
{% extends 'base.html' %}
{% load i18n %}

{% block meta_title %}{% trans "Choose Tasks" %}{% endblock %}
{% block title %}{% trans "Choose Tasks" %}{% endblock %}

{% block main %}
    <script>
    function pick(taskID) {
    //     console.log(taskID);
        var form = document.createElement('form');
        form.setAttribute('method', 'post');
        form.setAttribute('action', '/tasks/pick');
        form.style.display = 'hidden';
        var IDField = document.createElement("input");
        IDField.setAttribute("type", "hidden");
        IDField.setAttribute("name", "ID");
        IDField.setAttribute("value", taskID);
        form.appendChild(IDField);
        document.body.appendChild(form)
        form.submit();
    }
    </script>
    <button class="btn btn-info" type="button" onclick="window.location.href='/tasks/add'">Add new task</button>
    {% for task in tasks %}
        <div class="post">
            <h3><a href="{% url 'task_detail' pk=task.pk %}">{{ task.title }}</a></h3>
            {% if task.completed %}
            <p style="color:green">Completed</p>
            {% endif %}
            <p>{{ task.desc|linebreaks }}</p>
            <input class="btn btn-success" type="submit" value="Select this task" onclick="pick('{{task.id}}')">
        </div>
    {% endfor %}
{% endblock main %}

cooking/tasks/templates/task_details.html
{% extends 'base.html' %}
{% load i18n %}

{% block meta_title %}My tasks{% endblock %}
{% block title %}Task detail: {{task.title}}{% endblock %}

{% block breadcrumb_menu %}
<li class="active">{% trans "Home.Tasks" %}</li>
{% endblock %}

{% block main %}

<!-- Tried to use DELETE but too much hassle getting it to work -->
<!-- <script>
function del(taskID) {
//     $.ajax({
//     url: '',
//     type: 'DELETE',
//     success: function(result) {
//     }
//});
    var form = document.createElement('form');
    form.setAttribute('method', 'DELETE');
    form.setAttribute('action', '/tasks/task/{{task.id}}');
    form.style.display = 'hidden';
    var IDField = document.createElement("input");
    IDField.setAttribute("type", "hidden");
    IDField.setAttribute("name", "ID");
    IDField.setAttribute("value", taskID);
    form.appendChild(IDField);
    document.body.appendChild(form);
    console.log(form);
    form.submit();
}
</script> -->

<div class="post">
    <h1><a href="{% url 'task_detail' pk=task.pk %}">{{ task.title }}</a></h1>
    <p>{{ task.desc|linebreaks }}</p>
    <p>Difficulty: {{ task.get_diff_display }}</p>
    <p>Type: {{ task.task_type }}</p>
<!--     <input class="btn btn-danger" type="submit" value="Delete this task" onclick="del('{{task.id}}')"> -->
    {% if task.user = request.user %}
    <button class="btn btn-danger" type="submit" value="Delete this task" onclick="if(confirm('Are you sure you want to delete this task?'))window.location.href='/tasks/delete/{{task.id}}'" formmethod="GET">Delete this task</button>
    {% endif %}

</div>
{% endblock main %}